#!/bin/sh

#export GLFW_IM_MODULE=ibus
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export QT4_IM_MODULE=fcitx
#export KWIN_OPENGL_INTERFACE=egl
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
#export KWIN_TRIPLE_BUFFER=1
#export KWIN_COMPOSE=O2
export GDK_DPI_SCALE=1.5
export GDK_BACKEND=wayland
export XWAYLAND_NO_GLAMOR=1
XDG_SESSION_TYPE=wayland startplasma-wayland #dbus-run-session startplasma-wayland 
